services:
  postgres:
    image: pgvector/pgvector
    container_name: container
    environment:
      POSTGRES_DB: POSTGRES_DB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: POSTGRES_PASSWORD
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/athena_data

  app:
    build: .
    container_name: container_name
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - "8083:8000"
    volumes:
      - ./:/app
    working_dir: /app
    command: python run.py

volumes:
  pgdata: